version: '2'

services:
  keys:
    build: "ssh"

  tweek-blackbox:
    image: soluto/tweek-blackbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/testRepoData:/repo
    environment:
      - GATEWAY_PORT=1111

  js_tests:
    build: .
    depends_on:
      - tweek-blackbox
    environment:
      - TWEEK_GATEWAY_URL=http://gateway

  dotnet_tests:
    build: ./dotnet
    depends_on:
      - tweek-blackbox
    environment:
      - TWEEK_GATEWAY_URL=http://gateway
    command: bash -c "cd Tweek.Client.Tests && dotnet test"
